version: "3.9"  

services:
#config backend (nodejs)
  back:
    build: ./backend  
    container_name: back
    hostname: back
    ports:
      - "8080:8080"
    depends_on:
      - mongo
#config srvmong
  mongo:
    build: ./srvmongo

    container_name: mongo
    hostname: mongo
#config front (nginx)
  front:
    build: ./frontend
    container_name: front
    hostname: front
    ports:
      - "80:80"

